### PR TITLE
Social media website - Milestone: friendships v2 

### PR DESCRIPTION
**Pull request by jebitok-dev**
In this milestone, I worked on the mutual friendships by:-

- adding has_many relationships and new methods on User Model.
- adding changes to the User's controller and views.

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there :)
First of all, I'd like to say big congrats for making such great work and effort to reach this milestone in this project 👍 
 Second is the **highlights** of what you accomplished so far on this milestone:-

1. Your models' associations are perfectly set up.
2. Mutual friends method is correct.
3. Extracting the logic in the rails helpers is outstanding.
4. Timeline posts logic is just fine.
However tho, there are still a few more changes to make in order to get this milestone approved and move on to the next 😊🙏
Please keep up the great work 💪

<hr>

- [ ] When I create a new post, an error occurs pointing out missing ```like_or_dislike_btn(post)``` method in the post partial file. It seems like you accidentally deleted it from the application helper. Kindly fix this issue.
- [ ] Currently, I cannot find a way to make a complete Friendship, It stuck at pending friendship request. Also, I cannot find buttons to accept or reject a request. Please include those in both All Users and User's Profile pages. Please fix these issues in order to make it possible for a user to send, accept, and/or reject a friendship request successfully!
- [ ] There are 27 failure test cases in your project. Kindly make sure to fix them.

<hr>

## **OPTIONAL**

- The ```timeline_posts``` private method inside the posts controller, It's better to assign it inside the Post/User model or the helpers since it's not related to the RESTful operations that the controllers are made to handle. 😊

<hr>

Kindly make the required changes, then ask for another CRR 👍 
Good luck and happy coding 👨‍💻💻

<hr>

Please feel free to contact me on **Slack** with the name **"Mahmoud Bakr"** in case you got any questions related to my above comments.

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

### Hello @jebitok-dev, you have done great job so far but we still have some things to change and improve, kindly find them below:

- [ ] In my case I have 3 users: `gzim`, `mina`, `mila` and `mila` sends friendship requests to both `gzim` and `mina` and then when I login as `mina` and go to the gzim's profile I can see that `mila` has already send him a friendship requests and I can see both accept and reject buttons which is not right because `mina` should not have this option to choose for `gzim`.
Screenshot from 2021-03-20 13-22-30
- [ ] Please update the update in UsersController because whenever I try to `accept` or `reject` a friendship I get the following error: 
Screenshot from 2021-03-20 13-24-20
- [ ] You have 29 cases of tests failing, kindly fix them

Please fix the required changes and ask for another code review whenever you're ready

_**If you have any question related to the required changes feel free to text me on slack @GzimAsani** or just add a comment here_

HAPPY CODING :computer: :desktop_computer:

**Comment by jebitok-dev** [comment]
One user signs up at a time when you have more than one user(s) you'll have to sign out the current one in order to send/accept/reject friend requests on the other account.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
You made a tremendous improvement to this project by working on the requested changes. Well done!
You managed to address the logic errors as pointed out. Let's make some changes to our test cases.
- [ ] Right now you have some failing test cases: 
```
rspec ./spec/feature/comment_spec.rb:8 # comments_controller creates one comment
rspec ./spec/feature/friendrequest_spec.rb:9 # friendrequests_controller adds a friend
rspec ./spec/feature/friendrequest_spec.rb:15 # friendrequests_controller accepts friend request
rspec ./spec/feature/friendrequest_spec.rb:24 # friendrequests_controller rejects friend request
rspec ./spec/feature/friendrequest_spec.rb:33 # friendrequests_controller lists all friends of user
rspec ./spec/feature/like_spec.rb:8 # likes_controller likes one post
rspec ./spec/feature/like_spec.rb:16 # likes_controller dislikes one post
rspec ./spec/feature/post_spec.rb:8 # posts_controller creates one post
rspec ./spec/feature/user_spec.rb:8 # users_controller signs up  a user
rspec ./spec/feature/user_spec.rb:13 # users_controller logs in a user
rspec ./spec/feature/user_spec.rb:18 # users_controller logs out a user
```


### Martin Afani
#### Slack: whiz25

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- [ ] No logic in views :+1: 

To Improve :factory_worker:

- [ ] Hey team, sorry but I was not able to run your APP :cry:  because I got some errors when I tried to create the DB. As I faced this issue for the first time, I don't know if it happens just on my local or if it is bug in your APP but I suggest that you try to fix it:


That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @jebitok-dev**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
