### PR TITLE
Social media website - Milestone: friendships v1

### PR DESCRIPTION
**Pull request by jebitok-dev**
In this milestone I:-
- setup the Postgresql database
- created the friend request associations and enabled users to send friend requests and accept.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Invalid PR 😞 
Hey, @jebitok-dev nice work setting up the project but I have to mark this PR as invalid because you didn't setup code linters.
Please setup the linters using Github actions and make sure there are no errors. Learn more [here](https://medium.com/@OwenTran/github-workflow-for-rails-ci-34209a53d19e)


### Martin Afani
#### Slack: whiz25

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @jebitok-dev  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [ ] The user's list page should contain a list of all users (including the current user)
* [ ] The `Add friend` button on the single user page is not working. It keeps redirecting to the user's list page. The button on the user's list page is also not working. Kindly fix that.


### Make the required changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @jebitok-dev :handshake: :handshake: :handshake: 

#### :warning: You need to implement the requested changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ]  The user's list page should contain a list of all users (including the current user)
- [ ] The Add friend button on the single user page is not working. It keeps redirecting to the user's list page. The button on the user's list page is also not working. Kindly fix that.
# [Optional changes] :yellow_circle: 
- [ ] It would be very nice if you add the currently logged in user email in navbar
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by jebitok-dev** [comment]
Hello, I'm having a hard time fixing the button_to to redirect to the helpers

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Comment by jebitok-dev** [comment]
Thank you team for your assistance through the code review feedback.

**Pull request merged**
